on: 
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          MERGE_LABELS: ""
          MERGE_REQUIRED_APPROVALS: "1"
          MERGE_RETRIES: "7"
          MERGE_RETRY_SLEEP: "10000"
