on: 
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      name:
        required: true
        type: string
      type:
        default: 'develop'
        description: 'Value can be develop | staging | staging-hotfix'
        type: string
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      HOST:
        required: true
      DOCKER_USERNAME:
        required: true
      DOCKER_PASSWORD:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    
      - name: Clone repository - Staging
        run: git clone -b develop git@github.com:${{ github.repository_owner }}/${{ inputs.name }}.git .
        if: ${{ inputs.type == 'staging' }}
        
      - name: Clone repository - Staging [HotFix]
        run: git clone -b staging git@github.com:${{ github.repository_owner }}/${{ inputs.name }}.git .
        if: ${{ inputs.type == 'staging-hotfix' }}
    
      - name: Checkout
        uses: actions/checkout@v2
        if: ${{ inputs.type == 'develop' }}

      - uses: actions/cache@v3
        with:
          path: "node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('yarn.lock') }}
          
      - name: Setup git
        run: |
          git config --global user.name Christian Curi
          git config --global user.email c.christiancuri@gmail.com
          
      - name: Push version to staging branch
        if: ${{ inputs.type == 'staging' }}
        run: |
          git checkout -b staging
          echo " " >> RELEASE.md
          git add .
          git commit -m "ci(release): staging [ci skip]" --no-verify
          git push -u origin staging -f

      - name: Get common files
        run: |
          git clone git@github.com:Zellim-Project/common-deploy-files.git
          cp common-deploy-files/backend/* .
          rm -rf common-deploy-files

      - name: Setup ssh hosts
        run: ssh-keyscan -t rsa ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: Deleting github folder
        run: rm -rf .git

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: zellim/${{ inputs.name }}:${{ github.sha }}

      - name: Update Environment
        run: |
          ssh -tt ${{ inputs.username }}@${{ secrets.HOST }} 'sudo -i -u root bash -c "
            kubectl set image deployment ${{ inputs.name }} ${{ inputs.name }}=zellim/${{ inputs.name }}:${{ github.sha }}
          "'
